build-collection, corex collection concept

diff --git a/scripts/build-collection.in b/scripts/build-collection.in
--- a/scripts/build-collection.in
+++ b/scripts/build-collection.in
@@ -150,7 +150,7 @@ error() {
 	exit 1
 }
 setup_pkgmk_conf() {
-cat > /$VERSION/$CHROOT/etc/pkgmk.conf << "EOF"
+cat > /$VERSION/$COLLECTION/etc/pkgmk.conf << "EOF"
 export CFLAGS="-O2 -pipe"
 export CXXFLAGS="${CFLAGS}"
 export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
@@ -169,68 +169,64 @@ EOF
 }
 setup_collection() {
 	local DIR
-	DIR="/$VERSION/$CHROOT"
+	DIR="/$VERSION/$COLLECTION"
 
-	if [ "$CHROOT" == "base" ]; then
-		COLLECTION="core"
-		echo "dir /DEPOT/base
+	if [ "$COLLECTION" == "base" ]; then
+		GIT="x86_64-sysV"
+		echo "dir /DEPOT/$COLLECTION
 base /DEPOT/base
 logdir /LOGS" > $DIR/etc/cards.conf || exit 1
 		return
 	fi
-	if [ "$CHROOT" == "cli" ]; then
-		COLLECTION="core"
-		echo "dir /DEPOT/cli
+	if [ "$COLLECTION" == "cli" ]; then
+		GIT="core"
+		echo "dir /DEPOT/$COLLECTION
 dir /DEPOT/base
 base /DEPOT/base
 logdir /LOGS" > $DIR/etc/cards.conf || exit 1
 		return
 	fi
-	if [ "$CHROOT" == "gui" ]; then
-		COLLECTION="core"
-		echo "dir /DEPOT/gui
+	if [ "$COLLECTION" == "gui" ]; then
+		GIT="core"
+		echo "dir /DEPOT/$COLLECTION
 dir /DEPOT/cli
 dir /DEPOT/base
 base /DEPOT/base
 logdir /LOGS" > $DIR/etc/cards.conf || exit 1
 		return
 	fi
-	if [ "$CHROOT" == "systemd" ]; then
-		COLLECTION="core"
-		echo "dir /DEPOT/systemd
+	if [ "$COLLECTION" == "cli-extra" ]; then
+		GIT="extra"
+		echo "dir /DEPOT/$COLLECTION
+dir /DEPOT/cli
+dir /DEPOT/base
+base /DEPOT/base
+logdir /LOGS" > $DIR/etc/cards.conf || exit 1
+		return
+	fi
+	if [ "$COLLECTION" == "gui-extra" ]; then
+		GIT="extra"
+		echo "dir /DEPOT/$COLLECTION
+dir /DEPOT/gui
+dir /DEPOT/cli
+dir /DEPOT/base
+base /DEPOT/base
+logdir /LOGS" > $DIR/etc/cards.conf || exit 1
+		return
+	fi
+	if [ "$COLLECTION" == "nonfree" ]; then
+		echo "dir /DEPOT/$COLLECTION
 dir /DEPOT/gui
 dir /DEPOT/cli
 dir /DEPOT/base
 base /DEPOT/base
 base /DEPOT/cli
 base /DEPOT/gui
-base /DEPOT/systemd
 logdir /LOGS" > $DIR/etc/cards.conf || exit 1
 		return
 	fi
-	if [ "$CHROOT" == "cli-extra" ]; then
-		COLLECTION="extra"
-		echo "dir /DEPOT/cli-extra
-dir /DEPOT/cli
-dir /DEPOT/base
-base /DEPOT/base
-logdir /LOGS" > $DIR/etc/cards.conf || exit 1
-		return
-	fi
-	if [ "$CHROOT" == "gui-extra" ]; then
-		COLLECTION="extra"
-		echo "dir /DEPOT/gui-extra
-dir /DEPOT/gui
-dir /DEPOT/cli-extra
-dir /DEPOT/cli
-dir /DEPOT/base
-base /DEPOT/base
-logdir /LOGS" > $DIR/etc/cards.conf || exit 1
-		return
-	fi
-
-	echo "dir /DEPOT/$CHROOT-extra
-dir /DEPOT/$CHROOT
+	echo "dir /DEPOT/$COLLECTION-extra
+dir /DEPOT/$COLLECTION
 dir /DEPOT/gui
 dir /DEPOT/cli
 dir /DEPOT/base
@@ -275,58 +271,55 @@ fi
 
 VERSION=`dirname $1`
 VERSION=`basename $VERSION`
-CHROOT=`basename $1`
-COLLECTION="$CHROOT"
+COLLECTION=`basename $1`
+GIT="$COLLECTION"
 
 mkdir -p $1/etc || exit 1
 
-if [ "$CHROOT" == "base" ] \
-|| [ "$CHROOT" == "cli"  ] \
-|| [ "$CHROOT" == "gui"  ]; then
-	setup_collection
+setup_collection
+
+if [ "$GIT" == "x86_64-sysV" ] \
+|| [ "$GIT" == "core"  ] \
+|| [ "$GIT" == "extra" ] \
+|| [ "$GIT" == "nonfree" ]; then
 	DEVEL="cards.devel \
-	&& cd /root/$COLLECTION \
-	&& bash scripts/$CHROOT"
-fi
-if [ "$CHROOT" == "systemd"  ]; then
-	setup_collection
-	DEVEL="cards.devel && pkgrm eudev && pkgrm eudev.devel \
-	&& cards install systemd && cards install systemd.devel \
-	&& cd /root/$COLLECTION && bash scripts/$CHROOT"
-fi
-if [ "$CHROOT" == "cli-extra"  ] \
-|| [ "$CHROOT" == "gui-extra"  ]; then
-	setup_collection
+&& cd /root/$GIT \
+&& bash scripts/$COLLECTION"
+	if [ $# -gt 1 ]; then
+		DEVEL="$DEVEL $2"
+	else
+		DEVEL="$DEVEL -a"
+	fi
+else
 	DEVEL="cards.devel \
-	&& cd /root/$COLLECTION \
-	&& bash scripts/$CHROOT"
-fi
-if [ "$COLLECTION" != "core" ] \
-&& [ "$COLLECTION" != "extra"  ]; then
-	setup_collection
-	DEVEL="cards.devel \
-	&& cd /root/$CHROOT \
-	&& bash scripts/$COLLECTION -a \
-	&& bash scripts/$COLLECTION-extra"
+&& cd /root/$GIT \
+&& bash scripts/$COLLECTION -a \
+&& bash scripts/$COLLECTION-extra -a"
 fi
 
 setup_pkgmk_conf
 
-
-if [ $# -gt 1 ]; then
-	DEVEL="$DEVEL $2"
-else
-	DEVEL="$DEVEL -a"
-fi
-
 export DEVEL VERSION
 
-echo "CHROOT: $CHROOT"
-echo "COLLECTION: $COLLECTION"
-echo "VERSION: $VERSION"
+GIT_PROJ=`grep ^/home /etc/fstab |grep $1/|cut -d " " -f1`
+if [ -z "$GIT_PROJ" ]; then
+	echo ">>> Cannot rsync, $1 not found in /etc/fstab"
+	error $1
+fi
+
+echo ""
+echo " cards.conf:"
+cat /$VERSION/$COLLECTION/etc/cards.conf
+echo ""
+echo " COLLECTION: $COLLECTION"
+echo "GIT Project: $GIT"
+echo "    VERSION: $VERSION"
 echo "The command: KERNEL="NONE" LFS="$1" DEPOT="/DEPOT" install-nutyx"
-echo -n "DEVEL: $DEVEL "
-echo -n " OK ? (y) "
+echo "      DEVEL: $DEVEL "
+echo ""
+echo "The rsync  : rsync -a --exclude .git $GIT_PROJ/ $1/root/$GIT/"
+echo ""
+echo -n "  OK ? (y) : "
 read a
 
 if [ "$a" != "y" ]; then
@@ -360,15 +353,10 @@ else
 fi
 MOUNT_POINTS="$MOUNT_POINTS $1/sources"
 
-mkdir -p $1/root/$COLLECTION || error $1
-GIT_PROJ=`grep ^/home /etc/fstab |grep $1/|cut -d " " -f1`
-echo "rsync -a --delete --exclude .git $GIT_PROJ/ $1/root/$COLLECTION/"
-if [ -z "$GIT_PROJ" ]; then
-	echo ">>> Cannot rsync, not set"
-	error $1
-fi
-rsync -a --delete --exclude .git $GIT_PROJ/ $1/root/$COLLECTION/ || error "rsync"
-chown -R 1000:1000 $1/root/$COLLECTION/ || error "chown $1/root/$COLLECTION"
+mkdir -p $1/root/$GIT || error $1
+rsync -a --exclude .git $GIT_PROJ/ $1/root/$GIT/ || error "rsync"
+echo "chown -R 1000:1000 $1/root/$GIT"
+chown -R 1000:1000 $1/root/$GIT/
 
 KERNEL="NONE" LFS="$1" DEPOT="/DEPOT" install-nutyx || error $1
 
