mybld cleanup time.

diff --git a/scripts/mybld.in b/scripts/mybld.in
--- a/scripts/mybld.in
+++ b/scripts/mybld.in
@@ -14,7 +14,7 @@ OPTIONS
               Ask for confirmation.
 
       -p, --pause
-              Make a pause after enter in to the chroot.
+              Make a pause after entering the chroot.
 
       -n, --new <collection>/<package> [version] [description] [url] [sources]
               Create a new <collection>/<package>/Pkgfile.
@@ -33,6 +33,9 @@ OPTIONS
 
       -s, --sync <collection>
              Synchronize all the binaries of the <collection>.
+
+      -v, --verbose
+             Show all possibles actions in install-nutyx script.
 
 MORE INFO
        mybld(8)
@@ -247,8 +250,12 @@ parse_arguments() {
 
     -p|--pause)
       MANUAL="yes"
-      PAUSE=" && printf \"You are now in the chroot.\n\
+      PAUSE="&& printf \"You are now in the chroot.\n\
 Type exit when finish.\n\n Good Luck !!!\n\n\" && bash";;
+
+    -v|--verbose)
+      VERBOSE="yes"
+      echo "====> You want verbose mode on install-nutyx command:" ;;
 
     -I|--init)
       INIT="yes";;
@@ -262,6 +269,7 @@ Type exit when finish.\n\n Good Luck !!!\n\n\" && bash";;
 "
         exit 1
       fi
+      echo "====> You want to know if the '$1' collection is clean:"
       PARAM+=($1);;
 
     -s|--sync)
@@ -277,7 +285,8 @@ Type exit when finish.\n\n Good Luck !!!\n\n\" && bash";;
 
     -A|--ask)
       CONFIRM="yes"
-      echo "====> you ask confirmation" ;;
+      VERBOSE="yes"
+      echo "====> You ask for confirmation:" ;;
 
     -h|--help)
       usage
@@ -326,14 +335,17 @@ remove_all() {
 		[ -d $ROOT/${VERSION}/${COLLECTION}/${i} ] || continue
 		mountpoint -q $ROOT/${1}/${i}  || continue
 		sudo umount -R $ROOT/${1}/${i} || exit 1
-
 	done
 	for FOLDER in $ROOT/${VERSION}/${COLLECTION}/* ; do
 		[ -d ${FOLDER} ] || continue
 		! mountpoint -q ${FOLDER} || continue
 		sudo rm -r $FOLDER || exit 1
-  	done
-	rm -d $ROOT/${VERSION}/${COLLECTION} || exit 1
+	done
+	for f in "$(find $ROOT/${VERSION}/${COLLECTION}/)"; do
+		[ "$f" == "$ROOT/${VERSION}/${COLLECTION}/" ] && break
+        rm -i $f
+	done
+    rm -d $ROOT/${VERSION}/${COLLECTION} || exit 1
 	echo "
 >>>   $ROOT/${VERSION}/${COLLECTION} cleanup successfully ...
 "
@@ -446,8 +458,7 @@ bs ca cs cy da de el es fi fr ga gl gn he hi hr hu ia id is it \
 ja ka kk km kn ko lt lv mk ml mr ms my nl nn oc or pa pt pl rm \
 ro ru rw si sq sk sl sr sv ta te th tr uk ur uz vi xh zh"
 
-  PKGMK_CONF='
-export CFLAGS="-O2 -pipe"
+  PKGMK_CONF='export CFLAGS="-O2 -pipe"
 export CXXFLAGS="${CFLAGS}"
 export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
 PKGMK_CLEAN="no"
@@ -655,8 +666,7 @@ if ! [ -O "$ROOT/$VERSION" ]; then
 fi
 
 setup_cards_conf
-DEVEL="cd /$GIT \
-$PAUSE "
+DEVEL="cd /$GIT $PAUSE"
 
 if [ -z $MANUAL ]; then
   DEVEL+="&& cards create"
@@ -682,36 +692,33 @@ fi
 setup_pkgmk_conf
 
 export DEVEL VERSION
-echo ""
+[ "$VERBOSE" == "yes" ] || QUIET="-q"
+
 if [ -f $HOME/.mybld ];then
   echo " $HOME/.mybld:
  =================================
 "
-
   cat $HOME/.mybld
 else
-  echo ">>>       $HOME/.mybld not found"
+  echo "====> Config file $HOME/.mybld not found"
 fi
-echo ""
-echo " pkgmk.conf:
- ==========="
-echo "$PKGMK_CONF"
-echo ""
-echo " cards.conf:
- ==========="
-echo "$CARDS_CONF"
-echo ""
-echo " COLLECTION: $COLLECTION"
-echo "GIT Project: $GIT_PROJ"
-echo "    VERSION: $VERSION"
-echo "      DEVEL: $DEVEL "
-echo "  ROOTMOUNT: $ROOTMOUNT"
-echo "The command: KERNEL=\"NONE\" LFS=\"$ROOT/${VERSION}/${COLLECTION}\" DEPOT=\"/DEPOT\" DEVEL=\"$DEVEL\" install-nutyx -t"
-echo ""
-echo " install-nutyx:
- =============="
-KERNEL="NONE" LFS="$ROOT/${VERSION}/${COLLECTION}" DEPOT="/DEPOT" DEVEL="$DEVEL" install-nutyx -t
-echo ""
+echo "
+pkgmk.conf:
+===========
+$PKGMK_CONF
+
+cards.conf:
+===========
+$CARDS_CONF
+
+         COLLECTION: $COLLECTION
+        GIT Project: $GIT_PROJ
+            VERSION: $VERSION
+              DEVEL: $DEVEL
+          ROOTMOUNT: $ROOTMOUNT
+running the command: sudo KERNEL=\"NONE\" LFS=\"$ROOT/${VERSION}/${COLLECTION}\" \
+DEPOT=\"/DEPOT\" DEVEL=\"$DEVEL\" install-nutyx $QUIET
+"
 
 if [ -z "$PACKAGES_LIST" ]; then
   if [ ! -z "${PARAM[1]}" ]; then
@@ -755,7 +762,6 @@ if [ "$CONFIRM" == "yes" ]; then
   answer
 fi
 
-#
 ##### Main Config files ######
 mkdir -p "$ROOT/${VERSION}/${COLLECTION}/etc" || exit 1
 echo "$PKGMK_CONF" > $ROOT/$VERSION/$COLLECTION/etc/pkgmk.conf
@@ -861,7 +867,6 @@ else
 fi
 MOUNT_POINTS="$MOUNT_POINTS LOGS"
 
-
 mkdir -p $ROOT/${VERSION}/${COLLECTION}/sources || error /${VERSION}/${COLLECTION}
 if [ -d ${ROOTMOUNT}/sources ]; then
   sudo mount --bind ${ROOTMOUNT}/sources $ROOT/${VERSION}/${COLLECTION}/sources || \
@@ -878,10 +883,8 @@ error "mounting ${GIT_PROJ}"
 
 MOUNT_POINTS="$MOUNT_POINTS $GIT"
 
-echo 'running the command:
-sudo KERNEL=\"NONE\" LFS=\"$ROOT/${VERSION}/${COLLECTION}\" DEPOT=\"/DEPOT\" DEVEL=\"$DEVEL\" install-nutyx'
-sudo KERNEL="NONE" LFS="$ROOT/${VERSION}/${COLLECTION}" DEPOT="/DEPOT" DEVEL="$DEVEL" install-nutyx || \
-error "sudo KERNEL=\"NONE\" LFS=\"$ROOT/${VERSION}/${COLLECTION}\" DEPOT=\"/DEPOT\" DEVEL=\"$DEVEL\" install-nutyx"
+sudo KERNEL="NONE" LFS="$ROOT/${VERSION}/${COLLECTION}" DEPOT="/DEPOT" DEVEL="$DEVEL" install-nutyx $QUIET|| \
+error "sudo KERNEL=\"NONE\" LFS=\"$ROOT/${VERSION}/${COLLECTION}\" DEPOT=\"/DEPOT\" DEVEL=\"$DEVEL\" install-nutyx $QUIET"
 
 [ -z $MANUAL ] && ding
 umount_all
