need to commit what's done so far besoin de commiter ce qui est fait jusqu'à présent

diff --git a/scripts/pkgmk.in b/scripts/pkgmk.in
--- a/scripts/pkgmk.in
+++ b/scripts/pkgmk.in
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# .cards.tar
+#  cards
 # 
 #  Copyright (c) 2000-2005 Per Liden
 #  Copyright (c) 2006-2013 by CRUX team (http://crux.nu)
@@ -69,9 +69,6 @@ check_pkgfile() {
 	elif [ "$version" == "" ]; then
 		error "Variable 'version' not initiated or not found in $PKGMK_PKGFILE."
 		exit $E_PKGFILE
-	elif [ "$release" == "" ]; then
-		error "Variable 'release' not initiated or not found in $PKGMK_PKGFILE."
-		exit $E_PKGFILE
 	elif [ "`type -t build`" != "function" ]; then
 		error "Function 'build' not specified in $PKGMK_PKGFILE."
 		exit $E_PKGFILE
@@ -103,7 +100,7 @@ downloads_file_with_curl() {
 		exit $E_GENERAL
 	fi
 	DOWNLOAD_OPTS="--ftp-pasv --retry 3 --retry-delay 3 \
-	-o $1 --fail -#"
+	-R -o $1 --fail -#"
 
 	error=1
 
@@ -170,14 +167,15 @@ download_file() {
 	fi
 }
 sync_all_files() {
-	local DIR GROUP FILE URL
+	local DIR GROUP FILE URL DEPOT_URL
+	DIR=`dirname $PWD`
+	GROUP=`basename $DIR`
+	DEPOT_URL=`cat $CARDS_CONFFILE|grep ^dir|grep $DIR|cut -d " " -f2|cut -d "|" -f 2|sed "s/ //g"`
 	if [ ! "`type -p curl`" ]; then
 		error "Command 'curl' not found."
 		exit $E_GENERAL
 	fi
-	DIR=`dirname $PWD`
-	GROUP=`basename $DIR`
-	URL="$CARDS_DEPOT_URL/$GROUP/${name}_$version-$release"
+	URL="$DEPOT_URL/${name}@$version"
 	if [ ! -f $PKGMK_SIGNATURE ]; then
 		downloads_file_with_curl  $PKGMK_SIGNATURE $URL/$PKGMK_SIGNATURE
 	fi
@@ -250,20 +248,20 @@ get_package_list() {
 	local FILE i
 	i=0
 	if [ "$PKGMK_ARCH" == "x86_64" ]; then
-		for FILE in `find $PKGMK_PACKAGE_DIR -name "${name}*_$version-$release-x86_64.cards.tar.$PKGMK_COMPRESSION_MODE"`; do
-			TARGETS[i]=`basename $FILE`
-			i=$((i+1))
-		done
-		for FILE in `find $PKGMK_PACKAGE_DIR -name "${name}*_$version-$release-any.cards.tar.$PKGMK_COMPRESSION_MODE"`; do
+		for FILE in `find $PKGMK_PACKAGE_DIR -name "${name}*@*-x86_64.cards.tar.$PKGMK_COMPRESSION_MODE"`; do
 			TARGETS[i]=`basename $FILE`
 			i=$((i+1))
 		done
 	else
-		for FILE in `find $PKGMK_PACKAGE_DIR -name "${name}*_$version-$release-i686.cards.tar.$PKGMK_COMPRESSION_MODE"`; do
+		for FILE in `find $PKGMK_PACKAGE_DIR -name "${name}*@*-i686.cards.tar.$PKGMK_COMPRESSION_MODE"`; do
 			TARGETS[i]=`basename $FILE`
 			i=$((i+1))
 		done
 	fi
+	for FILE in `find $PKGMK_PACKAGE_DIR -name "${name}*@*-any.cards.tar.$PKGMK_COMPRESSION_MODE"`; do
+		TARGETS[i]=`basename $FILE`
+		i=$((i+1))
+	done
 	if [ -z $TARGETS ]; then
 		warning "Package(s) not found(s)..."
 	fi
@@ -421,7 +419,7 @@ check_footprint() {
 	fi
 	for TARGET in ${TARGETS[@]}; do
 		if [ -f $TARGET ]; then
-			PKGMK_FOOTPRINT="`echo $TARGET|cut -d "_" -f1`.`echo $TARGET|cut -d "-" -f3|cut -d "." -f1`.footprint"
+			PKGMK_FOOTPRINT="`echo $TARGET|cut -d "@" -f1`.`echo $TARGET|cut -d "-" -f3|cut -d "." -f1`.footprint"
 			make_footprint > $FILE.footprint
 			if [ -f $PKGMK_FOOTPRINT ]; then
 				sort -k 3 $PKGMK_FOOTPRINT > $FILE.footprint.orig
@@ -492,7 +490,7 @@ pack_lib() {
 			fi
 			if [ -d $DIR/$SUBDIR ]; then
 				bsdtar -r -f \
-				$PKGMK_PACKAGE_DIR/${name}.${group}_$version-$release-$PKGMK_ARCH.cards.tar \
+				$PKGMK_PACKAGE_DIR/${name}.${group}@$build-$PKGMK_ARCH.cards.tar \
 				$DIR/$SUBDIR || BUILD_SUCCESSFUL="no"
 				rm -r $DIR/$SUBDIR
 				j=1
@@ -510,7 +508,7 @@ pack_devel() {
 		for SUBDIR in include lib/pkgconfig; do
 			if [ -d $DIR/$SUBDIR ]; then
 				bsdtar -r -f \
-				$PKGMK_PACKAGE_DIR/${name}.${group}_$version-$release-any.cards.tar \
+				$PKGMK_PACKAGE_DIR/${name}.${group}@$PKGMK_BUILDVER-any.cards.tar \
 				$DIR/$SUBDIR || BUILD_SUCCESSFUL="no"
 				rm -r $DIR/$SUBDIR
 				j=1
@@ -524,7 +522,7 @@ pack_doc() {
 		for SUBDIR in doc gtk-doc; do
 			if [ -d $DIR/$SUBDIR ]; then
 				bsdtar -r -f \
-				$PKGMK_PACKAGE_DIR/${name}.${group}_$version-$release-any.cards.tar \
+				$PKGMK_PACKAGE_DIR/${name}.${group}@$PKGMK_BUILDVER-any.cards.tar \
 				$DIR/$SUBDIR || BUILD_SUCCESSFUL="no"
 				rm -r $DIR/$SUBDIR
 				j=1
@@ -538,7 +536,7 @@ pack_man() {
 		for SUBDIR in info man; do
 			if [ -d $DIR/$SUBDIR  ]; then
 				bsdtar -r -f \
-				$PKGMK_PACKAGE_DIR/${name}.${group}_$version-$release-any.cards.tar \
+				$PKGMK_PACKAGE_DIR/${name}.${group}@$PKGMK_BUILDVER-any.cards.tar \
 				$DIR/$SUBDIR || BUILD_SUCCESSFUL="no"
 				rm -r $DIR/$SUBDIR
 				j=1
@@ -550,7 +548,7 @@ pack_service() {
 	local DIR="etc/rc.d"
 	if [ -d $DIR ]; then
 		bsdtar -r -f \
-		$PKGMK_PACKAGE_DIR/${name}.${group}_$version-$release-any.cards.tar \
+		$PKGMK_PACKAGE_DIR/${name}.${group}@$PKGMK_BUILDVER-any.cards.tar \
 		$DIR || BUILD_SUCCESSFUL="no"
 		rm -r $DIR
 		j=1
@@ -559,17 +557,17 @@ pack_service() {
 compress_group_package() {
 	local ARCH
 	for ARCH in x86_64 i686 any; do
-		if [ -f $PKGMK_PACKAGE_DIR/${name}.${group}_$version-$release-$ARCH.cards.tar ]; then
+		if [ -f $PKGMK_PACKAGE_DIR/${name}.${group}@$PKGMK_BUILDVER-$ARCH.cards.tar ]; then
 			info "compress ${group}" 
 			case $PKGMK_COMPRESSION_MODE in
-				gz)  gzip -9 $PKGMK_PACKAGE_DIR/${name}.${group}_$version-$release-$ARCH.cards.tar;;
-				bz2) bzip2 -9  $PKGMK_PACKAGE_DIR/${name}.${group}_$version-$release-$ARCH.cards.tar;;
-				xz)  xz -z -9 $PKGMK_PACKAGE_DIR/${name}.${group}_$version-$release-$ARCH.cards.tar ;;
+				gz)  gzip -9 $PKGMK_PACKAGE_DIR/${name}.${group}@$PKGMK_BUILDVER-$ARCH.cards.tar;;
+				bz2) bzip2 -9  $PKGMK_PACKAGE_DIR/${name}.${group}@$PKGMK_BUILDVER-$ARCH.cards.tar;;
+				xz)  xz -z -9 $PKGMK_PACKAGE_DIR/${name}.${group}@$PKGMK_BUILDVER-$ARCH.cards.tar ;;
 			esac
-			TARGETS[i]="${name}.${group}_$version-$release-$ARCH.cards.tar.$PKGMK_COMPRESSION_MODE"
+			TARGETS[i]="${name}.${group}@$PKGMK_BUILDVER-$ARCH.cards.tar.$PKGMK_COMPRESSION_MODE"
 			info "Build result for ${TARGETS[i]}:"
 			bsdtar -t -v -f \
-			$PKGMK_PACKAGE_DIR/${name}.${group}_$version-$release-$ARCH.cards.tar.$PKGMK_COMPRESSION_MODE \
+			$PKGMK_PACKAGE_DIR/${name}.${group}@$PKGMK_BUILDVER-$ARCH.cards.tar.$PKGMK_COMPRESSION_MODE \
 			|| BUILD_SUCCESSFUL = "no"
 		fi
 	done
@@ -619,8 +617,8 @@ build_package() {
 					exit 1
 				fi
 			else
-				if [ -f $PKGMK_PACKAGE_DIR/${name}.${group}_$version-$release-* ]; then
-					rm $PKGMK_PACKAGE_DIR/${name}.${group}_$version-$release-*
+				if [ -f $PKGMK_PACKAGE_DIR/${name}.${group}@$PKGMK_BUILDVER-* ]; then
+					rm $PKGMK_PACKAGE_DIR/${name}.${group}@$PKGMK_BUILDVER-$PKGMK_BUILDVER-*
 				fi
 				pack_${group} 
 				if [ "$BUILD_SUCCESSFUL"  == "no" ]; then
@@ -642,14 +640,16 @@ build_package() {
 				if [ -f $PKGMK_ROOT/${name}.${group}.info ]; then
 					cp $SRC/${name}.${group}.info $PKG/.INFO
 				fi
-				SIZE_I="`du -b $PKGMK_PACKAGE_DIR/${name}.${group}_$version-$release-*|sed "s/\t/ /"|cut -d " " -f1`"
+				SIZE_I="`du -b $PKGMK_PACKAGE_DIR/${name}.${group}@$PKGMK_BUILDVER-*|sed "s/\t/ /"|cut -d " " -f1`"
 				echo "size_i = $SIZE_I" > $PKG/.META
+				echo "version = $version" >> $PKG/.META
+				echo "build = $PKGMK_BUILDVER" >> $PKG/.META
 
 				for file in .INFO .META .PRE .POST .README; do
 					if [ -f $file ]; then
 						bsdtar -r -f \
-						$PKGMK_PACKAGE_DIR/${name}.${group}_$version-$release-*.cards.tar \
-						$file  || abort_on_build "${name}.$loc_$version-$release"
+						$PKGMK_PACKAGE_DIR/${name}.${group}@$PKGMK_BUILDVER-*.cards.tar \
+						$file  || abort_on_build "${name}.${group}@$PKGMK_BUILDVER"
 						rm $file
 					fi
 				done
@@ -671,45 +671,62 @@ build_package() {
 			for loc in `cd usr/share/locale/ && ls`; do
 				# Need to double check because glibc for exemple create a file in this directory
 				if [ -d usr/share/locale/$loc ];then
+					SIZE_I="`du -b --summarize $PKG/usr/share/locale/$loc|sed "s/\t/ /"|cut -d " " -f1`"
 					LOCALE_GROUP=`echo $loc|sed "s/_/-/g"`
-					bsdtar -c $COMPRESSION -f \
-					$PKGMK_PACKAGE_DIR/${name}.${LOCALE_GROUP}_$version-$release-any.cards.tar.$PKGMK_COMPRESSION_MODE \
-					usr/share/locale/$loc || abort_on_build "${name}.${LOCALE_GROUP}_$version-$release-any.cards.tar.$PKGMK_COMPRESSION_MODE"
+					echo "size_i = $SIZE_I" > .META
+					echo "name = $name.$LOCALE_GROUP" >> .META
+					echo "version = $version" >> .META
+					echo "build = $PKGMK_BUILDVER" >> .META
+					bsdtar -r -f $PKGMK_PACKAGE_DIR/${name}.${LOCALE_GROUP}@$PKGMK_BUILDVER-any.cards.tar \
+					.META
+					bsdtar -r -f $PKGMK_PACKAGE_DIR/${name}.${LOCALE_GROUP}@$PKGMK_BUILDVER-any.cards.tar \
+					usr/share/locale/$loc || abort_on_build "${name}.${LOCALE_GROUP}@$PKGMK_BUILDVER-any.cards.tar"
 					rm -rf usr/share/locale/$loc
-					TARGETS[i]="${name}.${LOCALE_GROUP}_$version-$release-any.cards.tar.$PKGMK_COMPRESSION_MODE"
+					info "compress $PKGMK_PACKAGE_DIR/${name}.${LOCALE_GROUP}@$PKGMK_BUILDVER-any.cards.tar"
+					case $PKGMK_COMPRESSION_MODE in
+						gz)  gzip -9 $PKGMK_PACKAGE_DIR/${name}.${LOCALE_GROUP}@$PKGMK_BUILDVER-any.cards.tar;;
+						bz2) bzip2 -9  $PKGMK_PACKAGE_DIR/${name}.${LOCALE_GROUP}@$PKGMK_BUILDVER-any.cards.tar;;
+						xz)  xz -z -9 $PKGMK_PACKAGE_DIR/${name}.${LOCALE_GROUP}@$PKGMK_BUILDVER-any.cards.tar ;;
+					esac
+					TARGETS[i]="${name}.${LOCALE_GROUP}@$PKGMK_BUILDVER-any.cards.tar.$PKGMK_COMPRESSION_MODE"
 					info "Build result for ${TARGETS[i]}:"
 					i=$((i+1))
 					bsdtar -t -v -f \
-					$PKGMK_PACKAGE_DIR/${name}.${LOCALE_GROUP}_$version-$release-any.cards.tar.$PKGMK_COMPRESSION_MODE \
-					|| abort_on_build "${name}.${LOCALE_GROUP}_$version-$release-any.cards.tar.$PKGMK_COMPRESSION_MODE"
+					$PKGMK_PACKAGE_DIR/${name}.${LOCALE_GROUP}@$PKGMK_BUILDVER-any.cards.tar.$PKGMK_COMPRESSION_MODE \
+					|| abort_on_build "${name}.${LOCALE_GROUP}@$PKGMK_BUILDVER-any.cards.tar.$PKGMK_COMPRESSION_MODE"
 				fi
 			done
 		fi
-		TARGETS[i]="${name}_$version-$release-$PKGMK_ARCH.cards.tar.$PKGMK_COMPRESSION_MODE"
+		TARGETS[i]="${name}@$PKGMK_BUILDVER-$PKGMK_ARCH.cards.tar.$PKGMK_COMPRESSION_MODE"
 		add_metafiles
 		SIZE_I="`du -b --summarize $PKG|sed "s/\t/ /"|cut -d " " -f1`"
-		echo "size_i = $SIZE_I" > $PKG/.META || abort_on_build "${name}_$version-$release-$PKGMK_ARCH.cards.tar.$PKGMK_COMPRESSION_MODE"
+		echo "size_i = $SIZE_I" > $PKG/.META || abort_on_build "${name}@$PKGMK_BUILDVER-$PKGMK_ARCH.cards.tar.$PKGMK_COMPRESSION_MODE"
+		echo "version = $version" >> $PKG/.META
+		echo "name = $name " >> $PKG/.META
+		echo "build = $PKGMK_BUILDVER" >> $PKG/.META
 
 		# Need to sed otherwize it also takes the devel packages
-		echo  "run = `pkginfo --runtimedepfiles $PKG |sed "s/,[a-z]*.devel//g"`" >> $PKG/.META
+		for dep in `pkginfo --runtimedepfiles $PKG`; do
+			echo "run = $dep" >> $PKG/.META
+		done
 		
 		for file in .INFO .META .PRE .POST .README; do
 			if [ -f $file ]; then
-				bsdtar -r -f $PKGMK_PACKAGE_DIR/${name}_$version-$release-$PKGMK_ARCH.cards.tar \
+				bsdtar -r -f $PKGMK_PACKAGE_DIR/${name}@$PKGMK_BUILDVER-$PKGMK_ARCH.cards.tar \
 				$file
 			fi
 		done
 
-		bsdtar -r -f $PKGMK_PACKAGE_DIR/${name}_$version-$release-$PKGMK_ARCH.cards.tar *
+		bsdtar -r -f $PKGMK_PACKAGE_DIR/${name}@$PKGMK_BUILDVER-$PKGMK_ARCH.cards.tar *
 
-                info "compress $PKGMK_PACKAGE_DIR/${name}_$version-$release-$PKGMK_ARCH.cards.tar"
+                info "compress $PKGMK_PACKAGE_DIR/${name}@$PKGMK_BUILDVER-$PKGMK_ARCH.cards.tar"
 		case $PKGMK_COMPRESSION_MODE in
-			gz)  gzip -9 $PKGMK_PACKAGE_DIR/${name}_$version-$release-$PKGMK_ARCH.cards.tar;;
-			bz2) bzip2 -9  $PKGMK_PACKAGE_DIR/${name}_$version-$release-$PKGMK_ARCH.cards.tar;;
-			xz)  xz -z -9 $PKGMK_PACKAGE_DIR/${name}_$version-$release-$PKGMK_ARCH.cards.tar ;;
+			gz)  gzip -9 $PKGMK_PACKAGE_DIR/${name}@$PKGMK_BUILDVER-$PKGMK_ARCH.cards.tar;;
+			bz2) bzip2 -9  $PKGMK_PACKAGE_DIR/${name}@$PKGMK_BUILDVER-$PKGMK_ARCH.cards.tar;;
+			xz)  xz -z -9 $PKGMK_PACKAGE_DIR/${name}@$PKGMK_BUILDVER-$PKGMK_ARCH.cards.tar ;;
 		esac
-		info "Build result for $PKGMK_PACKAGE_DIR/${name}_$version-$release-$PKGMK_ARCH.cards.tar.$PKGMK_COMPRESSION_MODE:"
-		bsdtar -t -v -f $PKGMK_PACKAGE_DIR/${name}_$version-$release-$PKGMK_ARCH.cards.tar.$PKGMK_COMPRESSION_MODE
+		info "Build result for $PKGMK_PACKAGE_DIR/${name}@$PKGMK_BUILDVER-$PKGMK_ARCH.cards.tar.$PKGMK_COMPRESSION_MODE:"
+		bsdtar -t -v -f $PKGMK_PACKAGE_DIR/${name}@$PKGMK_BUILDVER-$PKGMK_ARCH.cards.tar.$PKGMK_COMPRESSION_MODE
 		if [ $? = 0 ]; then
 			BUILD_SUCCESSFUL="yes"
 			if [ "$PKGMK_IGNORE_FOOTPRINT" == "yes" ]; then
@@ -800,12 +817,7 @@ clean() {
 	done
 }
 clean_old() {
-	if [ "$PKGMK_ARCH" == "x86_64" ]; then
-		find $PKGMK_PACKAGE_DIR/${name}*#*-x86_64.cards.tar.* -exec rm -v {} \; 2> /dev/null
-		find $PKGMK_PACKAGE_DIR/${name}*#*-any.cards.tar.* -exec rm -v {} \; 2> /dev/null
-	else
-		find $PKGMK_PACKAGE_DIR/${name}*#*-i686.cards.tar.* -exec rm -v {} \; 2> /dev/null
-	fi
+	find $PKGMK_PACKAGE_DIR/${name}*.cards.tar* -exec rm -v {} \; 2> /dev/null
 }
 update_footprint() {
 	cd $PKGMK_PACKAGE_DIR
@@ -821,7 +833,7 @@ update_footprint() {
 			error "Unable to update footprint. File '$TARGET' not found."
 			exit 1
 		fi
-		PKGMK_FOOTPRINT="`echo $TARGET|cut -d "_" -f1`.`echo $TARGET|cut -d "-" -f3|cut -d "." -f1`.footprint"
+		PKGMK_FOOTPRINT="`echo $TARGET|cut -d "@" -f1`.`echo $TARGET|cut -d "-" -f3|cut -d "." -f1`.footprint"
 		check_file "$PKGMK_FOOTPRINT"
 		make_footprint > $PKGMK_FOOTPRINT
 		touch $TARGET
@@ -835,18 +847,12 @@ build_needed() {
 	RESULT="yes"
 	if [ -f $TARGET ]; then 
 		RESULT="no"
-	else
-		if [ "$PKGMK_CHECK_FILES" != "no" ]; then
-			for FILE in $PKGMK_PKGFILE ${source[@]}; do
-				FILE=`get_filename $FILE`
-				if [ ! -e $FILE ]; then
-					RESULT="yes"
-					break
-				fi
-			done
+		FILE=`get_filename $PKGMK_PKGFILE`
+		if [ ! -e $FILE ] || [ ! $TARGET -nt $FILE ]; then
+			RESULT="yes"
+			break
 		fi
 	fi
-
 	echo $RESULT
 }
 generate_md5sum()
@@ -871,12 +877,12 @@ update_index_html()
  <head>
   <meta charset="utf-8" />
 EOF
-echo "<title>${name} $version-$release</title>" >> $PKGMK_ROOT/index.html
+echo "<title>${name} $version</title>" >> $PKGMK_ROOT/index.html
 cat >> $PKGMK_ROOT/index.html << "EOF"
  </head>
  <body>
 EOF
-echo "<h4>${name} $version-$release `date +%Y%m%d`</h4>" >> $PKGMK_ROOT/index.html
+echo "<h4>${name} $version `date +%Y%m%d`</h4>" >> $PKGMK_ROOT/index.html
 echo -n "<pre><kbd>" >> $PKGMK_ROOT/index.html
 pushd $PKGMK_ROOT > /dev/null
 if [ -f  ${name}.info ]; then
@@ -1045,17 +1051,17 @@ main() {
 			exit 1
 		fi
 
-		CARDS_DEPOT_URL=`cat $CARDS_CONFFILE|grep url|cut -d " " -f2|sed "s/ //g"`
-		if [ "$CARDS_DEPOT_URL" == "" ]; then
-   			error "Variable url missing in $CARDS_CONFFILE"
-   			exit 1
-		fi
+#		CARDS_DEPOT_URL=`cat $CARDS_CONFFILE|grep url|cut -d " " -f2|sed "s/ //g"`
+#		if [ "$CARDS_DEPOT_URL" == "" ]; then
+#   			error "Variable url missing in $CARDS_CONFFILE"
+#   			exit 1
+#		fi
 
-		CARDS_DEPOT_DIR=`cat $CARDS_CONFFILE|grep dir|cut -d " " -f2|sed "s/ //g"`
-		if [ "$CARDS_DEPOT_DIR" == "" ]; then
-			error "Variable dir missing in $CARDS_CONFFILE"
-			exit 1
-		fi
+#		CARDS_DEPOT_DIR=`cat $CARDS_CONFFILE|grep dir|cut -d " " -f2|sed "s/ //g"`
+#		if [ "$CARDS_DEPOT_DIR" == "" ]; then
+#			error "Variable dir missing in $CARDS_CONFFILE"
+#			exit 1
+#		fi
 	fi
 	PKGMK_ARCH=`uname -m`
 	if ! (`which pkginfo > /dev/null`); then
@@ -1066,24 +1072,20 @@ main() {
 
 
 	PACKAGENAME=`basename $PKGMK_ROOT`
-	if [ "$PACKAGENAME" == "`echo $PACKAGENAME | cut  -d '_' -f1`" ];then
+	if [ "$PACKAGENAME" == "`echo $PACKAGENAME | cut  -d '@' -f1`" ];then
 		error "name not found when parsing the foldername"
 		exit $E_PKGFILE
 	fi
-	if [ "$PACKAGENAME" == "`echo $PACKAGENAME | cut  -d '-' -f2`" ];then
-		error "release not found when parsing the foldername"
+	if [ "$PACKAGENAME" == "`echo $PACKAGENAME | cut  -d '@' -f2`" ];then
+		error "version not found when parsing the foldername"
 		exit $E_PKGFILE
 	fi
-	name="`echo $PACKAGENAME | cut  -d "_" -f1`"
+	name="`echo $PACKAGENAME | cut  -d "@" -f1`"
 	
-	version="`basename $PKGMK_ROOT | cut -d "_" -f2 | cut -d "-" -f1`"
-
-	release="`basename $PKGMK_ROOT | cut -d "_" -f2 | cut -d "-" -f2`"
-
+	version="`basename $PKGMK_ROOT | cut -d "@" -f2`"
 
 	info "name: ${name}"
 	info "version: $version"
-	info "release: $release"
 
 	if [ "$PKGMK_RECURSIVE" = "yes" ]; then
 		recursive "$@"
@@ -1114,11 +1116,12 @@ main() {
 
 	check_pkgfile
 
+	get_package_list
+
 	case $PKGMK_COMPRESSION_MODE in
 		gz|bz2|xz)
-			get_package_list
 			if [ -z $TARGETS ]; then
-				TARGET="$PKGMK_PACKAGE_DIR/${name}_$version-$release-$PKGMK_ARCH.cards.tar.$PKGMK_COMPRESSION_MODE"
+				TARGET="$PKGMK_PACKAGE_DIR/${name}@$PKGMK_BUILDVER-$PKGMK_ARCH.cards.tar.$PKGMK_COMPRESSION_MODE"
 			fi;;
 		*)
 			error "Compression mode '$PKGMK_COMPRESSION_MODE' not supported"
@@ -1185,12 +1188,24 @@ main() {
 
 	fi
 	# From here on it's need to check the base package not any group which means
-	TARGET=$PKGMK_PACKAGE_DIR/${name}_$version-$release-$PKGMK_ARCH.cards.tar.$PKGMK_COMPRESSION_MODE
-	if [ "`build_needed`" = "no" ] && [ "$PKGMK_FORCE" = "no" ] && [ "$PKGMK_CHECK_MD5SUM" = "no" ]; then
-		info "Package '$TARGET' is up to date."
+	if [ -z $TARGETS ]; then
+		TARGET=$PKGMK_PACKAGE_DIR/${name}@$PKGMK_BUILDVER-$PKGMK_ARCH.cards.tar.$PKGMK_COMPRESSION_MODE
+		if [ "`build_needed`" = "no" ] && [ "$PKGMK_FORCE" = "no" ] && [ "$PKGMK_CHECK_MD5SUM" = "no" ]; then
+			info "Package '$TARGET' is up to date."
+		else
+			download_source
+			build_package
+		fi
 	else
-		download_source
-		build_package
+		for TARGET in ${TARGETS[@]}; do
+			if [ "`build_needed`" = "no" ] && [ "$PKGMK_FORCE" = "no" ] && [ "$PKGMK_CHECK_MD5SUM" = "no" ]; then
+				info "Package '$TARGET' is up to date."
+			else
+				download_source
+				build_package
+				break
+			fi
+		done
 	fi
 	if [ "$PKGMK_UPDATE_INDEX" != "no" ];then
 		update_index_html
@@ -1213,6 +1228,7 @@ readonly PKGMK_VERSION="#VERSION#"
 readonly PKGMK_COMMAND="$0"
 readonly PKGMK_ROOT="$PWD"
 
+PKGMK_BUILDVER=`date +%s`
 CARDS_CONFFILE="/etc/cards.conf"
 
 PKGMK_SIGNATURE="MD5SUM"
@@ -1222,7 +1238,6 @@ PKGMK_PKGFILE="Pkgfile"
 PKGMK_MD5SUM="`uname -m`.md5sum"
 PKGMK_NOSTRIP=".nostrip"
 
-PKGMK_CHECK_FILES="no"
 PKGMK_CLEAN_OLD="yes"
 
 PKGMK_SYNC_FILES="yes"
