As we know allready, some binaries cannot find automatically they deps , we need to define a new rule (and a new file): All the binaries which do not find all the dependencies automatically, they will be listed in the <name>.run. A good exemple is xorg-server, this guy will have both. xorg-server.deps for the compilation and xorg-server.run which will contain at least xorg-font
Comme on le sais déjà, certains binaires ne peuvent pas trouver toutes leurs dépendances automatiquement.
Nous avons donc besoin de définir une nouvelle règle (et un nouveau fichier): Tous les binaires qui ne trouvent
pas tous leur dependances automatiquement, ces même dépendances seront listés dans le fichier <nom>.run. Un bon
exemple est xorg-server, ce port aura les 2 xorg-server.deps pour la compile et xorg-server.run pour les dépendances
non trouvés auto comme xorg-font

diff --git a/scripts/pkgmk.in b/scripts/pkgmk.in
--- a/scripts/pkgmk.in
+++ b/scripts/pkgmk.in
@@ -33,6 +33,7 @@ E_MD5=6        # md5sum verification failed
 E_FOOTPRINT=7  # footprint check failure
 E_BUILD=8      # error while running 'build()'
 E_INSTALL=9    # error while installing the package via 'pkgadd'
+E_DEPS=10      # error while searching runtime deps via 'pkginfo -b'
 
 info() {
 	echo "=======> $1"
@@ -216,7 +217,7 @@ sync_all_files() {
 			FILE="`echo $LINE|cut -d ":" -f2`"
 			ARCH="`echo $LINE|cut -d ":" -f3`"
 			if [ "$ARCH" != "" ]; then
-				echo "$MD5SUM  ${FILE}${BUILD_DATE}-${ARCH}${EXT}" >> .md5
+				echo "$MD5SUM  ${FILE}${BUILD_DATE}${ARCH}${EXT}" >> .md5
 			else
 				echo  "$MD5SUM  ${FILE}" >> .md5
 			fi
@@ -619,6 +620,7 @@ add_meta_to_archive() {
 
 	bsdtar xf $PKGMK_PACKAGE_DIR/$1
 
+
 	SIZE_I="`du -b $PKGMK_PACKAGE_DIR/$1|sed "s/\t/ /"|cut -d " " -f1`"
 	DESCR="`head -1 $PKGMK_ROOT/${name}.info`"
 	echo "N$NAME" > .META
@@ -631,7 +633,19 @@ add_meta_to_archive() {
 	for dep in `pkginfo --runtimedepfiles $TAR`; do
 		echo "R$dep" >> .META
         done
-
+	
+	if [ -f $PKGMK_ROOT/${name}.run ]; then
+		info "Adding runtime deps to Archive $NAME"
+		for rd in `cat $PKGMK_ROOT/${name}.run`; do
+			if [ "`pkginfo -b $rd`" == "0" ] || [ "`pkginfo -b $rd`" == "" ]; then
+				error "Runtime dependencie $rd not found, cannot continue"
+				clean_up
+				exit $E_DEPS;
+			fi
+				
+			echo "R$rd`pkginfo -b $rd`" >> .META
+		done
+	fi
 	bsdtar -tf $PKGMK_PACKAGE_DIR/$1 > .MTREE
 
 	rm $PKGMK_PACKAGE_DIR/$1
@@ -733,8 +747,13 @@ build_package() {
 					fi
 				done
 			fi
-		done	
-		bsdtar -r -f $PKGMK_PACKAGE_DIR/${name}${PKGMK_BUILDVER}${PKGMK_ARCH}.${PKGMK_PACKAGE_EXT} *
+		done
+		if [ "`ls|wc -l`" != "0" ]; then
+			bsdtar -r -f $PKGMK_PACKAGE_DIR/${name}${PKGMK_BUILDVER}${PKGMK_ARCH}.${PKGMK_PACKAGE_EXT} *
+		else
+			error "No files found in $PKG..."
+			exit $E_BUILD
+		fi
 		if [ $? = 0 ]; then
 			BUILD_SUCCESSFUL="yes"
 			if [ "$PKGMK_IGNORE_FOOTPRINT" == "yes" ]; then
@@ -763,7 +782,7 @@ build_package() {
 			touch -r $PKGMK_ROOT/$PKGMK_PKGFILE $TARGET &> /dev/null
 		fi
 		error "Building '$TARGET' failed."
-		exit 1
+		exit $E_BUILD
 	fi
 }
 
@@ -838,7 +857,6 @@ clean_up() {
 			rm -v $PKGMK_PACKAGE_DIR/$TARGET
 		done
 	fi	
-#	find $PKGMK_PACKAGE_DIR/${name}*.$PKGMK_PACKAGE_EXT* -exec rm -v {} \; 2> /dev/null
 	find $PKGMK_ROOT -name "*.md5sum" -exec rm -v {} \; 2> /dev/null
 	find $PKGMK_ROOT -name "*.footprint" -exec rm -v {} \; 2> /dev/null
 	unset TARGETS
@@ -1152,11 +1170,9 @@ main() {
 		info "PKGMK_CLEANUP: $PKGMK_CLEANUP"
 	fi
 	if [ "$PKGMK_CLEANUP" != "no" ]; then
-# 		PKGMK_UPDATE_SIGNATURE="no"
 		PKGMK_IGNORE_FOOTPRINT="yes"
 		PKGMK_IGNORE_MD5SUM="yes"
 		warning "FOOTPRINT AND MD5SUM IGNORED"
-#		warning "MD5SUM file will not be generated"
 	else
 		info "PKGMK_UPDATE_SIGNATURE: $PKGMK_UPDATE_SIGNATURE"
 		info "PKGMK_IGNORE_FOOTPRINT: $PKGMK_IGNORE_FOOTPRINT"
