cards 2.87.0

diff --git a/scripts/pkgmk.in b/scripts/pkgmk.in
--- a/scripts/pkgmk.in
+++ b/scripts/pkgmk.in
@@ -751,20 +751,6 @@ add_meta_to_archive() {
 		echo "P$PACK" >> .META
 		echo "L$LICENSE" >> .META
 		echo "B$PKGMK_BUILDVER" >> .META
-	else
-	    echo "g$GROUP" >> .META
-		rds=("run_$GROUP[@]")
-		if [ ! -z "$(echo ${!rds})" ]; then
-			info "Adding runtime deps to Archive $NAME"
-			for rd in $(echo ${!rds}); do
-				if [ "$($PKGMK_PKGINFO -b $rd)" == "0" ] || [ "$($PKGMK_PKGINFO -b $rd)" == "" ]; then
-					error "Runtime dependency $rd not found, cannot continue"
-					clean
-					exit $E_DEPS;
-				fi
-				echo "R$rd$($PKGMK_PKGINFO -b $rd)" >> .META
-			done
-		fi
     fi
 
 	# TODO improve the pkginfo --runtimedepfiles functionnality
@@ -788,6 +774,21 @@ add_meta_to_archive() {
 				fi
 				echo "R$rd$(pkginfo -b $rd)" >> .META
 			done
+		fi
+		if [ ! -z "$GROUP" ]; then
+			echo "g$GROUP" >> .META
+			rds=("run_$GROUP[@]")
+			if [ ! -z "$(echo ${!rds})" ]; then
+				info "Adding runtime deps to Archive $NAME"
+				for rd in $(echo ${!rds}); do
+					if [ "$($PKGMK_PKGINFO -b $rd)" == "0" ] || [ "$($PKGMK_PKGINFO -b $rd)" == "" ]; then
+						error "Runtime dependency $rd not found, cannot continue"
+						clean
+						exit $E_DEPS;
+					fi
+					echo "R$rd$($PKGMK_PKGINFO -b $rd)" >> .META
+				done
+			fi
 		fi
 		for lib in $($PKGMK_PKGINFO --runtimelibs $TAR|grep -v ^[A-Z]); do
 			echo "l$lib" >> .META
