cards 1.0-rc1 finally

diff --git a/scripts/pkgmk.in b/scripts/pkgmk.in
--- a/scripts/pkgmk.in
+++ b/scripts/pkgmk.in
@@ -201,57 +201,6 @@ download_file() {
 		mv -f "$LOCAL_FILENAME_PARTIAL" "$LOCAL_FILENAME"
 	fi
 }
-sync_all_files() {
-	local LINE MD5SUM ARCH HEAD DIR FILE URL DEPOT_URL EXT BUILD_DATE TMPMD5
-	TMPMD5="/tmp/.md5"
-	if [ -f $TMPMD5 ]; then
-		rm $TMPMD5
-	fi
-	LINE=`dirname $PWD`
-	DIR=`cat $CARDS_CONFFILE|grep ^dir|grep $LINE|cut -d " " -f2|cut -d "|" -f 1|sed "s| ||g"`
-	if [ -z $DIR ]; then
-		error "$DIR not found in $CARDS_CONFFILE, cannot synchronise"
-		exit $E_GENERAL
-	fi
-	DEPOT_URL=`cat $CARDS_CONFFILE|grep ^dir|grep $LINE|cut -d " " -f2|sed "s|$DIR||"|sed "s| ||g"|sed "s,|,,"`
-	if [ -z $DEPOT_URL ]; then
-		warning "URL not found for $DIR in $CARDS_CONFFILE, ignore synchronising"
-	else
-		if [ ! "`type -p curl`" ]; then
-			error "Command 'curl' not found."
-			exit $E_GENERAL
-		fi
-		URL="$DEPOT_URL/${name}"
-		if [ ! -f $PKGMK_REPO ]; then
-			downloads_file_with_curl  $PKGMK_REPO $URL/$PKGMK_REPO
-		fi
-		HEAD=`head -1 $PKGMK_REPO`
-		if [ ${HEAD:10:1} = "#" ]; then # Packages availables
-			BUILD_DATE="`echo $HEAD|cut -d "#" -f1`"
-			EXT="`echo $HEAD|cut -d "#" -f2`"
-			for LINE in `cat $PKGMK_REPO`;do
-				MD5SUM="`echo $LINE|cut -d "#" -f1`"
-				FILE="`echo $LINE|cut -d "#" -f2`"
-				ARCH="`echo $LINE|cut -d "#" -f3`"
-				if [ "$ARCH" != "" ]; then
-					echo "$MD5SUM  ${FILE}${BUILD_DATE}${ARCH}${EXT}" >> $TMPMD5
-				else
-					echo  "$MD5SUM  ${FILE}" >> $TMPMD5
-				fi
-			done
-			sed -i "1d" $TMPMD5
-		else
-			sed  "s/#/  /" $PKGMK_REPO > $TMPMD5
-		fi
-		for FILE in $(cat $TMPMD5|cut -d " " -f 3);do
-			if [ ! -f $FILE ];then
-				downloads_file_with_curl $FILE $URL/$FILE
-				grep $FILE $TMPMD5|md5sum -c -|| exit $E_GENERAL
-			fi
-		done
-		rm $TMPMD5
-	fi
-}
 download_source() {
 	local FILE LOCAL_FILENAME
 
@@ -998,7 +947,7 @@ build_needed() {
 	echo $RESULT
 }
 
-update_category_repo()
+update_collection_repo()
 {
 	local HEAD BUILD_DATE VERSION RELEASE DESCRIPTION URL MAINTAINER PACKAGER EXTENSION
 	if [ -f $PKGMK_REPO ]; then
@@ -1035,9 +984,6 @@ update_repo()
 			fi
 		done
 		printf "\n" >> .PKGREPO
-		### TODO To make it compatible I will remove it sometimes
-		# echo "`get_package_builddate $TARGETS`:$EXT:$version" > MD5SUM
-		###
 		for TARGET in ${TARGETS[@]}; do
 			FILE=`basename $TARGET`
 			MD5SUM=`md5sum $TARGET|cut -d " " -f1`
@@ -1054,9 +1000,6 @@ update_repo()
 		rm -f $PKGMK_REPO
 	fi
 	echo "`md5sum Pkgfile|cut -d " " -f1`#Pkgfile" >> $PKGMK_REPO
-	### TODO To make it compatible
-	# echo "`md5sum Pkgfile|cut -d " " -f1`:Pkgfile" >> MD5SUM
-	###
 }
 clean_repo_files()
 {
@@ -1093,9 +1036,9 @@ print_help() {
 	echo "  -eo,  --extract-only        do not build, only extract source file(s)"
 	echo "  -utd, --up-to-date          do not build, only check if package is up to date"
 	echo "  -ur,  --update-repo         do not build, only update the $PKGMK_REPO file"
-	echo "  -uc,  --update-category     do not build, only update the $PKGMK_REPO file of the category means from the parent directory"
+	echo "  -uc,  --update-collection   do not build, only update the $PKGMK_REPO file of the collection means from the parent directory"
 	echo "  -uf,  --update-footprint    update footprint using result from last build"
-	echo "  -ic,  --ignore-category     build packages without update the $PKGMK_REPO file of the category means from the parent directory"
+	echo "  -ic,  --ignore-collection     build packages without update the $PKGMK_REPO file of the collection means from the parent directory"
 	echo "  -if,  --ignore-footprint    build packages without checking footprint"
 	echo "  -in,  --ignore-new          build packages, ignore new files in a footprint missmatch"
 	echo "  -um,  --update-md5sum       update md5sum"
@@ -1129,8 +1072,8 @@ parse_options() {
 				PKGMK_SHOW_VERSION="yes";;
 			-utd|--up-to-date)
 				PKGMK_UP_TO_DATE="yes" ;;
-			-uc|--update-category)
-				PKGMK_UPDATE_CATEGORY="yes";;
+			-uc|--update-collection)
+				PKGMK_UPDATE_COLLECTION="yes";;
 			-ur|--update-repo)
 				PKGMK_UPDATE_REPO="yes" ;;
 			-uf|--update-footprint)
@@ -1143,8 +1086,8 @@ parse_options() {
 				PKGMK_UPDATE_MD5SUM="yes" ;;
 			-im|--ignore-md5sum)
 				PKGMK_IGNORE_MD5SUM="yes" ;;
-			-ic|--ignore-category)
-				PKGMK_IGNORE_CATEGORY="yes" ;;
+			-ic|--ignore-collection)
+				PKGMK_IGNORE_COLLECTION="yes" ;;
 			-ir|--ignore-repo)
 				PKGMK_IGNORE_REPO="yes" ;;
 			-cm|--check-md5sum)
@@ -1190,11 +1133,9 @@ main() {
                 exit $E_GENERAL
         fi
         . $PKGMK_CONFFILE
-	if [ "$PKGMK_SYNC_FILES" == "yes" ]; then
-		if [ ! -f $CARDS_CONFFILE ]; then
-			error "$CARDS_CONFFILE not found"
-			exit $E_GENERAL
-		fi
+	if [ ! -f $CARDS_CONFFILE ]; then
+		error "$CARDS_CONFFILE not found"
+		exit $E_GENERAL
 	fi
 	PKGMK_ARCH=`uname -m`
 	if ! (`which pkginfo > /dev/null`); then
@@ -1208,10 +1149,6 @@ main() {
 	if [ "$PKGMK_RECURSIVE" = "yes" ]; then
 		recursive "$@"
 		exit 0
-	fi
-	if [ "$PKGMK_SYNC_FILES" == "yes" ]; then
-		warning  "PKGMK_SYNC_FILES: $PKGMK_SYNC_FILES"
-		[ "$PKGMK_FORCE" == "yes" ] || sync_all_files
 	fi
 	if [ ! -f $PKGMK_PKGFILE  ]; then
 		error "File '$PKGMK_PKGFILE' not found."
@@ -1316,8 +1253,8 @@ main() {
 		update_repo
 		exit 0
 	fi
-	if [ "$PKGMK_UPDATE_CATEGORY" = "yes" ]; then
-		update_category_repo
+	if [ "$PKGMK_UPDATE_COLLECTION" = "yes" ]; then
+		update_collection_repo
 		exit 0
 	fi
 	if [ "$PKGMK_UPDATE_REPO" = "yes" ]; then
@@ -1426,8 +1363,8 @@ main() {
 	if [ "$PKGMK_IGNORE_REPO" != "yes" ] && [ "$PKGMK_CLEAN" != "yes" ]; then
 		update_repo
 	fi
-	if [ "$PKGMK_IGNORE_CATEGORY" != "yes" ]; then
-		update_category_repo
+	if [ "$PKGMK_IGNORE_COLLECTION" != "yes" ]; then
+		update_collection_repo
 	fi
 	exit 0
 }
@@ -1455,7 +1392,6 @@ PKGMK_NOSTRIP=".nostrip"
 
 PKGMK_KEEP_SOURCES="no"
 PKGMK_CLEAN="yes"
-PKGMK_SYNC_FILES="no"
 
 
 PKGMK_GROUPS=()
@@ -1463,14 +1399,13 @@ PKGMK_LOCALES=(fr)
 
 PKGMK_SOURCE_MIRRORS=()
 PKGMK_SOURCE_DIR="$PWD"
-PKGMK_CATEGORY="$PWD"
 PKGMK_WORK_DIR="$PWD/work"
 PKGMK_DOWNLOAD="no"
 PKGMK_IGNORE_FOOTPRINT="yes"
 PKGMK_IGNORE_NEW="yes"
 PKGMK_IGNORE_MD5SUM="yes"
 PKGMK_IGNORE_REPO="no"
-PKGMK_IGNORE_CATEGORY="yes"
+PKGMK_IGNORE_COLLECTION="yes"
 
 PKGMK_NO_STRIP="no"
 
